apiVersion: snowdrop.dev/v1alpha1
kind: Database
metadata:
  name: my-db
spec:
  compositionSelector:
    matchLabels:
      provider: local
      type: dev
  parameters:
    type: postgresql
    version: 11.9.1
    namespace: db
