name: Checkout, jdk installation and maven build

on:
  workflow_call:

jobs:
  build_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          { 'version': '17', 'opts': '' }
        ]
    name: build with jdk ${{matrix.java.version}}

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/setup-java@v3
        name: set up jdk ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven

      - name: build with maven
        run: mvn clean install -Pvalidate-format